//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSkills2017
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUsers
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateTimeLogin { get; set; }
        public string Cause { get; set; }
        public System.DateTime DateTimeExit { get; set; }
        public string Reason { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
